### ISSUE TITLE
In Open Refine 3.4 this fails and throws an Internal Server Error 500

### ISSUE THREAD

**Issue by cluedindev** [CennoxX/netcore-reconciliation-service#1]
![image](https://user-images.githubusercontent.com/8896436/94438103-f31a9c00-019e-11eb-9870-8f4940395787.png)

**Comment by CennoxX** [comment]
Thanks for the report. Is the error thrown by Open Refine? What exactly did you do to get the error? I am running the Reconciling Service with Open Refine 3.4.1 without problems.

**Comment by marielmat** [comment]
I actually receive this error message from OpenRefine : 
![image](https://user-images.githubusercontent.com/61242683/104389441-73280000-5509-11eb-9f2a-78950242f8ba.png)

I'm a beginner, so I might be the one who is doing something wrong. Any help or advice would be appreciated. Thank you :)

**Comment by cluedindev** [comment]
> Thanks for the report. Is the error thrown by Open Refine? What exactly did you do to get the error? I am running the Reconciling Service with Open Refine 3.4.1 without problems.

Yes, it is thrown by Open Refine itself and it is triggered when you first enter the screen to do the reconciliation. The good news is, I THINK I have found the issue. The URL to IMDB in the lookup doesn't seem to be a valid way to get data from IMDB anymore and this is less of a Open Refine 3.4.1 issue and more related to that.

**Comment by CennoxX** [comment]
@cluedindev: Which URL do you think is not valid?
@marielmat: Do you see the service metadata JSON if you open http://localhost:5000/imdbreconcile/api in the browser?

**Comment by CennoxX** [comment]
if there is more information about the error, please open this issue again.
