### ISSUE TITLE
increase number of actors fetched

### ISSUE THREAD

**Issue by tdombos** [CennoxX/netcore-reconciliation-service#2]
The extension service currently fetches 3 actors only. Is it possible to increase this number?

**Comment by CennoxX** [comment]
The service gets all actors from the JSON-LD of the IMDb page (take a look at the JSON-LD in the HTML of the page). The JSON-LD of IMDb contains only rudimentary info about the movie/series. If more actors/info should be loaded, this cannot be done with the JSON-LD, but has to be done with parsing the HTML page or something like that.
